# Use postgres/example user/password credentials
version: '3.9'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: notectl
    ports:
      - '5433:5432'
    volumes:
      - 'db_data:/var/lib/postgresql'
      - './database:/docker-entrypoint-initdb.d'


volumes:
  db_data:


